name: evse-controller
services:
  controller:
    build: .
    volumes:
      - data:/c/data
    environment:
      - EVSE_DATA_DIR=/c/data
    ports:
      - "5000:5000"
      - "5001:5001"

volumes:
  data:

